import "dotenv/config";
import express from "express";
import Stripe from "stripe";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { db, transaction } from "./lib/db.js";
import { SESSION_COOKIE, hashPassword, verifyPassword, randomToken, tokenHash, parseCookies, sessionCookie } from "./lib/auth.js";
import { membershipPrice, applicationFee } from "./lib/pricing.js";

const app=express(), port=Number(process.env.PORT||4242), baseUrl=(process.env.BASE_URL||`http://localhost:${port}`).replace(/\/$/,"");
const stripe=process.env.STRIPE_SECRET_KEY ? new Stripe(process.env.STRIPE_SECRET_KEY) : null;
const fail=(status,message)=>Object.assign(new Error(message),{status});
const cleanEmail=v=>String(v||"").trim().toLowerCase();
const requiredStripe=()=>{if(!stripe)throw fail(503,"Stripe is not configured.");return stripe};
async function currentUser(req){const token=parseCookies(req.headers.cookie)[SESSION_COOKIE];if(!token)return null;const {rows}=await db().query(`SELECT u.id,u.email,u.role,u.display_name FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now() AND u.disabled_at IS NULL`,[tokenHash(token)]);return rows[0]||null}
const auth=(...roles)=>async(req,res,next)=>{try{req.user=await currentUser(req);if(!req.user)throw fail(401,"Sign in required.");if(roles.length&&!roles.includes(req.user.role))throw fail(403,"You do not have permission for this action.");next()}catch(e){next(e)}};

// Raw signed webhooks must precede JSON parsing. A stored event ID makes retries idempotent.
app.post("/webhooks/stripe",express.raw({type:"application/json"}),async(req,res,next)=>{try{const s=requiredStripe(), secret=process.env.STRIPE_WEBHOOK_SECRET;if(!secret)throw fail(503,"STRIPE_WEBHOOK_SECRET is not configured.");const event=s.webhooks.constructEvent(req.body,req.headers["stripe-signature"],secret);await transaction(async c=>{const inserted=await c.query("INSERT INTO webhook_events(stripe_event_id,event_type) VALUES($1,$2) ON CONFLICT DO NOTHING RETURNING stripe_event_id",[event.id,event.type]);if(!inserted.rowCount)return;const o=event.data.object;if(event.type==="checkout.session.completed"&&o.metadata?.booking_id)await c.query("UPDATE bookings SET status='booked',stripe_payment_intent_id=$1 WHERE id=$2 AND stripe_checkout_session_id=$3",[o.payment_intent,o.metadata.booking_id,o.id]);if(event.type.startsWith("customer.subscription.")){const status=event.type==="customer.subscription.deleted"?"canceled":o.status;await c.query("UPDATE memberships SET status=$1,current_period_end=to_timestamp($2),updated_at=now() WHERE stripe_subscription_id=$3",[status,o.current_period_end||0,o.id])}});res.json({received:true})}catch(e){next(e)}});
app.use(express.json({limit:"64kb"}));

app.post("/api/auth/signup",async(req,res,next)=>{try{const role=req.body?.role;if(!["customer","provider"].includes(role))throw fail(400,"Choose a customer or provider account.");const email=cleanEmail(req.body.email), name=String(req.body.display_name||"").trim();if(!/^\S+@\S+\.\S+$/.test(email)||!name)throw fail(400,"A valid email and display name are required.");const password=hashPassword(req.body.password);const token=randomToken();const user=await transaction(async c=>{const {rows}=await c.query("INSERT INTO users(email,password_hash,role,display_name) VALUES($1,$2,$3,$4) RETURNING id,email,role,display_name",[email,password,role,name]);if(role==="provider")await c.query("INSERT INTO provider_profiles(user_id) VALUES($1)",[rows[0].id]);await c.query("INSERT INTO sessions(user_id,token_hash,expires_at) VALUES($1,$2,now()+interval '14 days')",[rows[0].id,tokenHash(token)]);return rows[0]});res.setHeader("Set-Cookie",sessionCookie(token));res.status(201).json({user})}catch(e){if(e.code==="23505")e=fail(409,"An account with that email already exists.");next(e)}});
app.post("/api/auth/login",async(req,res,next)=>{try{const {rows}=await db().query("SELECT * FROM users WHERE lower(email)=$1 AND disabled_at IS NULL",[cleanEmail(req.body.email)]), user=rows[0];if(!user||!verifyPassword(String(req.body.password||""),user.password_hash))throw fail(401,"Email or password is incorrect.");const token=randomToken();await db().query("INSERT INTO sessions(user_id,token_hash,expires_at) VALUES($1,$2,now()+interval '14 days')",[user.id,tokenHash(token)]);res.setHeader("Set-Cookie",sessionCookie(token));res.json({user:{id:user.id,email:user.email,role:user.role,display_name:user.display_name}})}catch(e){next(e)}});
app.post("/api/auth/logout",auth(),async(req,res,next)=>{try{const token=parseCookies(req.headers.cookie)[SESSION_COOKIE];await db().query("DELETE FROM sessions WHERE token_hash=$1",[tokenHash(token)]);res.setHeader("Set-Cookie",sessionCookie("",0));res.status(204).end()}catch(e){next(e)}});
app.get("/api/me",auth(),(req,res)=>res.json({user:req.user}));
app.post("/api/auth/recovery",async(req,res,next)=>{try{const {rows}=await db().query("SELECT id FROM users WHERE lower(email)=$1",[cleanEmail(req.body.email)]);if(rows[0]){const token=randomToken();await db().query("INSERT INTO recovery_tokens(user_id,token_hash,expires_at) VALUES($1,$2,now()+interval '1 hour')",[rows[0].id,tokenHash(token)]);if(process.env.NODE_ENV!=="production")res.setHeader("X-Recovery-Token",token)}res.json({message:"If the account exists, recovery instructions have been queued."})}catch(e){next(e)}});
app.post("/api/auth/reset",async(req,res,next)=>{try{const password=hashPassword(req.body.password), hash=tokenHash(String(req.body.token||""));const result=await transaction(async c=>{const {rows}=await c.query("UPDATE recovery_tokens SET used_at=now() WHERE token_hash=$1 AND used_at IS NULL AND expires_at>now() RETURNING user_id",[hash]);if(!rows[0])throw fail(400,"Recovery link is invalid or expired.");await c.query("UPDATE users SET password_hash=$1 WHERE id=$2",[password,rows[0].user_id]);await c.query("DELETE FROM sessions WHERE user_id=$1",[rows[0].user_id]);return true});res.json({reset:result})}catch(e){next(e)}});

app.get("/api/dashboard",auth(),async(req,res,next)=>{try{const bookings=await db().query("SELECT id,starts_at,status,amount_cents,provider_id,customer_id FROM bookings WHERE customer_id=$1 OR provider_id=$1 ORDER BY starts_at DESC",[req.user.id]);const notifications=await db().query("SELECT id,kind,subject,body,read_at,created_at FROM notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 30",[req.user.id]);res.json({user:req.user,bookings:bookings.rows,notifications:notifications.rows})}catch(e){next(e)}});
app.post("/api/care-recipients",auth("customer"),async(req,res,next)=>{try{const name=String(req.body.preferred_name||"").trim();if(!name)throw fail(400,"Preferred name is required.");const {rows}=await db().query("INSERT INTO care_recipients(customer_id,preferred_name,relationship,notes) VALUES($1,$2,$3,$4) RETURNING id,preferred_name,relationship,created_at",[req.user.id,name,req.body.relationship||null,req.body.notes||null]);res.status(201).json({care_recipient:rows[0]})}catch(e){next(e)}});
app.get("/api/care-recipients",auth("customer"),async(req,res,next)=>{try{const {rows}=await db().query("SELECT id,preferred_name,relationship,created_at FROM care_recipients WHERE customer_id=$1 ORDER BY created_at",[req.user.id]);res.json({care_recipients:rows})}catch(e){next(e)}});
app.put("/api/provider/profile",auth("provider"),async(req,res,next)=>{try{const b=req.body,{rows}=await db().query("UPDATE provider_profiles SET bio=$2,experience_years=$3,service_zips=$4,service_types=$5,qualifications=$6,availability=$7 WHERE user_id=$1 RETURNING *",[req.user.id,String(b.bio||""),b.experience_years||null,b.service_zips||[],b.service_types||[],b.qualifications||[],b.availability||{}]);res.json({profile:rows[0]})}catch(e){next(e)}});
app.post("/api/requests",auth("customer"),async(req,res,next)=>{try{const b=req.body, own=await db().query("SELECT 1 FROM care_recipients WHERE id=$1 AND customer_id=$2",[b.care_recipient_id,req.user.id]);if(!own.rowCount)throw fail(404,"Care recipient not found.");const starts=new Date(b.starts_at);if(!b.service_type||!/^\d{5}$/.test(b.zip)||Number.isNaN(+starts)||starts<=new Date())throw fail(400,"Service, five-digit ZIP, and future start time are required.");const clinical=Boolean(b.clinical);const qualifications=clinical?[...(b.required_qualifications||[]),"licensed"]:b.required_qualifications||[];const {rows}=await db().query("INSERT INTO service_requests(customer_id,care_recipient_id,service_type,zip,starts_at,duration_minutes,clinical,required_qualifications) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *",[req.user.id,b.care_recipient_id,b.service_type,b.zip,starts,b.duration_minutes,clinical,[...new Set(qualifications)]]);res.status(201).json({request:rows[0]})}catch(e){next(e)}});
app.get("/api/requests/:id/matches",auth("customer"),async(req,res,next)=>{try{const request=await db().query("SELECT * FROM service_requests WHERE id=$1 AND customer_id=$2",[req.params.id,req.user.id]);if(!request.rowCount)throw fail(404,"Request not found.");const r=request.rows[0];const {rows}=await db().query(`SELECT u.id,u.display_name,p.bio,p.experience_years,p.service_types,p.qualifications,p.verification_status,p.rating,p.review_count FROM provider_profiles p JOIN users u ON u.id=p.user_id WHERE p.verification_status='verified' AND $1=ANY(p.service_zips) AND $2=ANY(p.service_types) AND p.qualifications @> $3::text[] AND NOT EXISTS(SELECT 1 FROM bookings b WHERE b.provider_id=p.user_id AND b.status<>'canceled' AND tstzrange(b.starts_at,b.ends_at,'[)') && tstzrange($4::timestamptz,$4::timestamptz+($5||' minutes')::interval,'[)')) ORDER BY p.rating DESC NULLS LAST,u.display_name`,[r.zip,r.service_type,r.required_qualifications,r.starts_at,r.duration_minutes]);res.json({matches:rows})}catch(e){next(e)}});
app.post("/api/requests/:id/select",auth("customer"),async(req,res,next)=>{try{const s=requiredStripe(),amount=Number(req.body.amount_cents),bps=Number(process.env.SERVICE_COMMISSION_BPS);const fee=applicationFee(amount,bps);const booking=await transaction(async c=>{const rq=await c.query("SELECT * FROM service_requests WHERE id=$1 AND customer_id=$2 AND status='open' FOR UPDATE",[req.params.id,req.user.id]);if(!rq.rowCount)throw fail(409,"Request is unavailable or already selected.");const r=rq.rows[0], provider=await c.query("SELECT stripe_account_id,payments_enabled,verification_status FROM provider_profiles WHERE user_id=$1 AND $2=ANY(service_zips) AND $3=ANY(service_types) AND qualifications @> $4::text[]",[req.body.provider_id,r.zip,r.service_type,r.required_qualifications]);if(!provider.rowCount||provider.rows[0].verification_status!=="verified")throw fail(400,"Provider is not eligible for this request.");if(!provider.rows[0].payments_enabled)throw fail(409,"Provider cannot accept payments yet.");const end=new Date(+new Date(r.starts_at)+r.duration_minutes*60000);const {rows}=await c.query("INSERT INTO bookings(request_id,customer_id,provider_id,starts_at,ends_at,amount_cents,commission_cents) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *",[r.id,req.user.id,req.body.provider_id,r.starts_at,end,amount,fee]);await c.query("UPDATE service_requests SET status='selected' WHERE id=$1",[r.id]);rows[0].stripe_account_id=provider.rows[0].stripe_account_id;return rows[0]});const session=await s.checkout.sessions.create({mode:"payment",line_items:[{price_data:{currency:"usd",product_data:{name:"MayBridge care service"},unit_amount:booking.amount_cents},quantity:1}],payment_intent_data:{application_fee_amount:booking.commission_cents,transfer_data:{destination:booking.stripe_account_id}},metadata:{booking_id:booking.id},success_url:`${baseUrl}/?booking=success`,cancel_url:`${baseUrl}/?booking=canceled`},{idempotencyKey:`booking-${booking.id}`});await db().query("UPDATE bookings SET stripe_checkout_session_id=$1 WHERE id=$2",[session.id,booking.id]);res.status(201).json({booking_id:booking.id,checkout_url:session.url})}catch(e){next(e)}});
app.post("/api/bookings/:id/complete",auth("provider"),async(req,res,next)=>{try{const {rows}=await db().query("UPDATE bookings SET status='provider_completed' WHERE id=$1 AND provider_id=$2 AND status='in_progress' RETURNING id,status",[req.params.id,req.user.id]);if(!rows[0])throw fail(409,"Only an in-progress service can be completed.");res.json({booking:rows[0]})}catch(e){next(e)}});
app.post("/api/bookings/:id/confirm",auth("customer"),async(req,res,next)=>{try{const {rows}=await db().query("UPDATE bookings SET status='completed',customer_confirmed_at=now(),completed_at=now() WHERE id=$1 AND customer_id=$2 AND status='provider_completed' RETURNING id,status",[req.params.id,req.user.id]);if(!rows[0])throw fail(409,"This service is not ready for confirmation.");res.json({booking:rows[0]})}catch(e){next(e)}});
app.post("/api/bookings/:id/review",auth("customer"),async(req,res,next)=>{try{const rating=Number(req.body.rating);if(!Number.isInteger(rating)||rating<1||rating>5)throw fail(400,"Rating must be from 1 to 5.");const review=await transaction(async c=>{const booking=await c.query("SELECT provider_id FROM bookings WHERE id=$1 AND customer_id=$2 AND status='completed'",[req.params.id,req.user.id]);if(!booking.rowCount)throw fail(403,"Only completed services may be reviewed.");const {rows}=await c.query("INSERT INTO reviews(booking_id,customer_id,provider_id,rating,body) VALUES($1,$2,$3,$4,$5) RETURNING *",[req.params.id,req.user.id,booking.rows[0].provider_id,rating,String(req.body.body||"").slice(0,2000)]);await c.query("UPDATE provider_profiles SET rating=(SELECT avg(rating) FROM reviews WHERE provider_id=$1),review_count=(SELECT count(*) FROM reviews WHERE provider_id=$1) WHERE user_id=$1",[booking.rows[0].provider_id]);return rows[0]});res.status(201).json({review})}catch(e){next(e)}});
app.post("/api/memberships/checkout",auth("customer"),async(req,res,next)=>{try{const interval=req.body.interval,amount=membershipPrice(interval),price=interval==="monthly"?process.env.STRIPE_MONTHLY_PRICE_ID:process.env.STRIPE_ANNUAL_PRICE_ID;if(!price)throw fail(503,`Stripe ${interval} membership price is not configured.`);const s=requiredStripe();let customer=(await db().query("SELECT stripe_customer_id FROM users WHERE id=$1",[req.user.id])).rows[0].stripe_customer_id;if(!customer){customer=(await s.customers.create({email:req.user.email,name:req.user.display_name,metadata:{user_id:req.user.id}})).id;await db().query("UPDATE users SET stripe_customer_id=$1 WHERE id=$2",[customer,req.user.id])}const session=await s.checkout.sessions.create({customer,mode:"subscription",line_items:[{price,quantity:1}],metadata:{user_id:req.user.id,interval,expected_amount_cents:String(amount)},success_url:`${baseUrl}/?membership=success`,cancel_url:`${baseUrl}/?membership=canceled`},{idempotencyKey:`membership-${req.user.id}-${interval}`});res.json({checkout_url:session.url})}catch(e){next(e)}});

app.use(express.static(path.join(path.dirname(fileURLToPath(import.meta.url)),"public")));
app.use((err,req,res,next)=>{if(res.headersSent)return next(err);const status=err.status||(err.code==="23505"?409:500);if(status>=500)console.error(err.message);res.status(status).json({error:status>=500?"The service is temporarily unavailable.":err.message})});
if(process.env.NODE_ENV!=="test")app.listen(port,()=>console.log(`MayBridge marketplace listening at ${baseUrl}`));
export { app };
